services:
  - mysql
  - postgresql

language: go

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on

go:
  - tip
  - 1.13.x
  - 1.15.x

addons:
  homebrew:
    update: true
    packages:
      - mysql
      - postgres

before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew services start mysql;
      brew services start postgres;
    fi

  - mysql -e 'CREATE DATABASE orm_test;'
  - psql -c 'CREATE DATABASE orm_test;' -U postgres

script: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success: bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
    - os: windows
