
build: off

clone_folder: c:\gopath\src\github.com\issue9\orm

environment:
  global:
    GOPATH: C:\gopath
    GO111MODULE: on
    CC: gcc.exe
  matrix:
    - GETH_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%

stack: go 1.11

test_script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
