name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: postgres
        ports:
          - 5432/tcp
      mysql:
        image: mysql:8.0
        ports:
          - 3306
    steps:

    - name: Install database
      run: |
        mysql -e 'CREATE DATABASE orm_test;'
        psql -c 'CREATE DATABASE orm_test;' -U postgres

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...
      
    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella 
