name: Sqlite
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # action 不支持非 linux 下的容器, windows-latest, macOS-latest
        go: ['1.18.x']


    steps:

      - name: 安装 Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -p=1 ./... -test.coverprofile=coverage.txt -covermode=atomic -dbs=sqlite3,sqlite

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
